/* 所有组件定义，依赖全局 Vue、Utils */

/* ── 模态框：新建播放列表 ── */
var CreatePlaylistModal = {
  name: 'CreatePlaylistModal',
  props: {
    name:        { type: String, default: '' },
    description: { type: String, default: '' }
  },
  emits: ['confirm', 'cancel', 'update:name', 'update:description'],
  template: [
    '<div>',
    '  <div class="modal fade show d-block" tabindex="-1" style="z-index:1055">',
    '    <div class="modal-dialog">',
    '      <div class="modal-content">',
    '        <div class="modal-header">',
    '          <h5 class="modal-title text-white">新建播放列表</h5>',
    '          <button type="button" class="btn-close btn-close-white" @click="$emit(\'cancel\')"></button>',
    '        </div>',
    '        <div class="modal-body">',
    '          <div class="mb-3">',
    '            <label class="form-label text-white">名称</label>',
    '            <input type="text" class="form-control" :value="name"',
    '                   @input="$emit(\'update:name\', $event.target.value)"',
    '                   placeholder="输入播放列表名称">',
    '          </div>',
    '          <div class="mb-3">',
    '            <label class="form-label text-white">描述（可选）</label>',
    '            <textarea class="form-control" rows="2" :value="description"',
    '                      @input="$emit(\'update:description\', $event.target.value)"',
    '                      placeholder="添加描述"></textarea>',
    '          </div>',
    '        </div>',
    '        <div class="modal-footer">',
    '          <button type="button" class="btn btn-outline-light" @click="$emit(\'cancel\')">取消</button>',
    '          <button type="button" class="btn btn-primary" @click="$emit(\'confirm\')">创建</button>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="modal-backdrop fade show" style="z-index:1050"></div>',
    '</div>'
  ].join('\n')
};

/* ── 模态框：快捷键说明 ── */
var ShortcutsModal = {
  name: 'ShortcutsModal',
  emits: ['close'],
  template: [
    '<div>',
    '  <div class="modal fade show d-block" tabindex="-1" style="z-index:1055">',
    '    <div class="modal-dialog modal-dialog-centered">',
    '      <div class="modal-content">',
    '        <div class="modal-header">',
    '          <h5 class="modal-title text-white"><i class="bi bi-keyboard me-2"></i>快捷键</h5>',
    '          <button type="button" class="btn-close btn-close-white" @click="$emit(\'close\')"></button>',
    '        </div>',
    '        <div class="modal-body">',
    '          <table class="table table-sm mb-0">',
    '            <tbody>',
    '              <tr><td><kbd>空格</kbd></td><td>播放 / 暂停</td></tr>',
    '              <tr><td><kbd>←</kbd> / <kbd>→</kbd></td><td>快退 / 快进 5 秒</td></tr>',
    '              <tr><td><kbd>↑</kbd> / <kbd>↓</kbd></td><td>音量 + / −</td></tr>',
    '              <tr><td><kbd>N</kbd></td><td>下一曲</td></tr>',
    '              <tr><td><kbd>P</kbd></td><td>上一曲</td></tr>',
    '              <tr><td><kbd>M</kbd></td><td>静音</td></tr>',
    '              <tr><td><kbd>L</kbd></td><td>显示 / 隐藏歌词</td></tr>',
    '              <tr><td><kbd>R</kbd></td><td>切换播放模式</td></tr>',
    '            </tbody>',
    '          </table>',
    '          <p class="text-secondary small mt-3 mb-0">* 输入框内快捷键无效</p>',
    '        </div>',
    '        <div class="modal-footer">',
    '          <button type="button" class="btn btn-outline-light" @click="$emit(\'close\')">关闭</button>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="modal-backdrop fade show" style="z-index:1050"></div>',
    '</div>'
  ].join('\n')
};

/* ── 导航栏 ── */
var NavBar = {
  name: 'NavBar',
  props: { user: Object },
  emits: ['logout'],
  template: [
    '<nav class="navbar navbar-expand-lg navbar-dark">',
    '  <div class="container-fluid">',
    '    <a class="navbar-brand" href="#">',
    '      <i class="bi bi-vinyl-fill"></i> Music Stream',
    '    </a>',
    '    <div class="d-flex align-items-center ms-auto gap-3">',
    '      <span class="text-secondary" style="font-size:14px">',
    '        欢迎，{{ user && (user.display_name || user.username) }}',
    '      </span>',
    '      <button class="btn btn-outline-light btn-sm" @click="$emit(\'logout\')">',
    '        <i class="bi bi-box-arrow-right"></i> 登出',
    '      </button>',
    '    </div>',
    '  </div>',
    '</nav>'
  ].join('\n')
};

/* ── 登录页 ── */
var LoginPage = {
  name: 'LoginPage',
  props: { loading: Boolean, error: String },
  emits: ['login', 'show-register'],
  data: function() { return { form: { username: '', password: '' } }; },
  template: [
    '<div class="login-container">',
    '  <div class="container">',
    '    <div class="row justify-content-center">',
    '      <div class="col-md-5 col-sm-8 col-11">',
    '        <div class="card">',
    '          <div class="card-body p-5">',
    '            <h3 class="text-center mb-2 text-white">',
    '              <i class="bi bi-vinyl-fill" style="color:var(--accent-green)"></i>',
    '            </h3>',
    '            <h4 class="text-center mb-1 text-white fw-bold">Music Stream</h4>',
    '            <p class="text-center text-secondary mb-4" style="font-size:13px">登录您的账号</p>',
    '            <div v-if="error" class="alert alert-danger py-2" style="font-size:13px">{{ error }}</div>',
    '            <form @submit.prevent="$emit(\'login\', form)">',
    '              <div class="mb-3">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">用户名</label>',
    '                <input type="text" class="form-control" v-model="form.username" required autofocus>',
    '              </div>',
    '              <div class="mb-4">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">密码</label>',
    '                <input type="password" class="form-control" v-model="form.password" required>',
    '              </div>',
    '              <button type="submit" class="btn btn-primary w-100" :disabled="loading">',
    '                <span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>',
    '                {{ loading ? "登录中..." : "登录" }}',
    '              </button>',
    '            </form>',
    '            <div class="text-center mt-4">',
    '              <a href="#" @click.prevent="$emit(\'show-register\')" class="text-secondary" style="font-size:13px">',
    '                还没有账号？立即注册',
    '              </a>',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 注册页 ── */
var RegisterPage = {
  name: 'RegisterPage',
  props: { loading: Boolean, error: String, success: String },
  emits: ['register', 'back-login'],
  data: function() {
    return { form: { email: '', username: '', display_name: '', password: '', confirm_password: '' } };
  },
  template: [
    '<div class="login-container">',
    '  <div class="container">',
    '    <div class="row justify-content-center">',
    '      <div class="col-md-5 col-sm-8 col-11">',
    '        <div class="card">',
    '          <div class="card-body p-5">',
    '            <h4 class="text-center mb-4 text-white fw-bold">',
    '              <i class="bi bi-person-plus me-2" style="color:var(--accent-green)"></i>用户注册',
    '            </h4>',
    '            <div v-if="error"   class="alert alert-danger  py-2" style="font-size:13px">{{ error }}</div>',
    '            <div v-if="success" class="alert alert-success py-2" style="font-size:13px">{{ success }}</div>',
    '            <form @submit.prevent="$emit(\'register\', form)">',
    '              <div class="mb-3">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">邮箱</label>',
    '                <input type="email" class="form-control" v-model="form.email" required>',
    '              </div>',
    '              <div class="mb-3">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">用户名</label>',
    '                <input type="text" class="form-control" v-model="form.username" required>',
    '              </div>',
    '              <div class="mb-3">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">显示名称</label>',
    '                <input type="text" class="form-control" v-model="form.display_name">',
    '              </div>',
    '              <div class="mb-3">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">密码</label>',
    '                <input type="password" class="form-control" v-model="form.password" required minlength="8">',
    '              </div>',
    '              <div class="mb-4">',
    '                <label class="form-label text-secondary" style="font-size:12px;text-transform:uppercase;letter-spacing:1px">确认密码</label>',
    '                <input type="password" class="form-control" v-model="form.confirm_password" required>',
    '              </div>',
    '              <button type="submit" class="btn btn-primary w-100" :disabled="loading">',
    '                {{ loading ? "注册中..." : "注册" }}',
    '              </button>',
    '            </form>',
    '            <div class="text-center mt-4">',
    '              <a href="#" @click.prevent="$emit(\'back-login\')" class="text-secondary" style="font-size:13px">返回登录</a>',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 歌曲列表 ── */
var TrackList = {
  name: 'TrackList',
  props: {
    tracks:       { type: Array,   default: function() { return []; } },
    playlists:    { type: Array,   default: function() { return []; } },
    favoritedIds: { type: Object,  default: function() { return new Set(); } },
    loading:      { type: Boolean, default: false }
  },
  emits: ['play', 'download', 'toggle-favorite', 'open-playlist-dropdown', 'add-to-playlist', 'create-playlist'],
  methods: {
    getCoverUrl:      function(id) { return Utils.getCoverUrl(id); },
    handleImageError: Utils.handleImageError,
    fmt:              function(s) { return Utils.formatDuration(s); },
    isFav:            function(id) { return this.favoritedIds.has(id); }
  },
  template: [
    '<div>',
    '  <div class="table-responsive">',
    '    <table class="table table-hover">',
    '      <thead>',
    '        <tr>',
    '          <th style="width:44px">#</th>',
    '          <th>标题</th>',
    '          <th style="width:150px">艺术家</th>',
    '          <th style="width:150px" class="d-none d-lg-table-cell">专辑</th>',
    '          <th style="width:70px">时长</th>',
    '          <th style="width:180px">操作</th>',
    '        </tr>',
    '      </thead>',
    '      <tbody>',
    '        <tr v-for="(track, idx) in tracks" :key="track.id">',
    '          <td class="text-secondary">{{ idx + 1 }}</td>',
    '          <td>',
    '            <div class="d-flex align-items-center gap-2">',
    '              <img :src="getCoverUrl(track.id)" class="cover-img"',
    '                   style="width:38px;height:38px;flex-shrink:0" @error="handleImageError">',
    '              <span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:200px">',
    '                {{ track.title }}',
    '              </span>',
    '            </div>',
    '          </td>',
    '          <td class="text-secondary" style="font-size:13px">{{ track.artist || "未知艺术家" }}</td>',
    '          <td class="text-secondary d-none d-lg-table-cell" style="font-size:13px">{{ track.album || "未知专辑" }}</td>',
    '          <td class="text-secondary" style="font-size:13px">{{ fmt(track.duration) }}</td>',
    '          <td>',
    '            <div class="action-btn-group">',
    '              <button class="btn btn-play btn-icon" @click="$emit(\'play\', track)" title="播放">',
    '                <i class="bi bi-play-fill"></i>',
    '              </button>',
    '              <button class="btn btn-icon btn-icon-ghost" @click="$emit(\'download\', track)" title="下载">',
    '                <i class="bi bi-download"></i>',
    '              </button>',
    '              <button class="btn btn-icon btn-icon-ghost" :class="{ \'fav-active\': isFav(track.id) }"',
    '                      @click="$emit(\'toggle-favorite\', track)"',
    '                      :title="isFav(track.id) ? \'取消收藏\' : \'收藏\'">',
    '                <i :class="isFav(track.id) ? \'bi bi-heart-fill\' : \'bi bi-heart\'"></i>',
    '              </button>',
    '              <div class="dropdown">',
    '                <button class="btn btn-icon btn-icon-ghost" type="button"',
    '                        data-bs-toggle="dropdown" aria-expanded="false"',
    '                        @click="$emit(\'open-playlist-dropdown\', track)"',
    '                        title="添加到播放列表">',
    '                  <i class="bi bi-plus-circle"></i>',
    '                </button>',
    '                <ul class="dropdown-menu dropdown-menu-end">',
    '                  <li v-if="!playlists.length">',
    '                    <span class="dropdown-item text-secondary" style="font-size:13px">暂无播放列表</span>',
    '                  </li>',
    '                  <li v-for="pl in playlists" :key="pl.id">',
    '                    <a class="dropdown-item" href="#" @click.prevent="$emit(\'add-to-playlist\', pl.id)">',
    '                      {{ pl.name }}',
    '                      <span class="badge bg-secondary ms-2">{{ pl.track_count || 0 }}</span>',
    '                    </a>',
    '                  </li>',
    '                  <li><hr class="dropdown-divider"></li>',
    '                  <li>',
    '                    <a class="dropdown-item" href="#" @click.prevent="$emit(\'create-playlist\')">',
    '                      <i class="bi bi-plus-lg me-2" style="color:var(--accent-green)"></i>新建播放列表',
    '                    </a>',
    '                  </li>',
    '                </ul>',
    '              </div>',
    '            </div>',
    '          </td>',
    '        </tr>',
    '      </tbody>',
    '    </table>',
    '  </div>',
    '  <div v-if="loading" class="text-center py-5">',
    '    <div class="spinner-border"></div>',
    '  </div>',
    '  <div v-if="!loading && !tracks.length" class="empty-state">',
    '    <i class="bi bi-inbox"></i>',
    '    暂无音乐文件',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 专辑网格 ── */
var AlbumGrid = {
  name: 'AlbumGrid',
  props: { albums: { type: Array, default: function() { return []; } } },
  emits: ['view-album'],
  methods: { handleImageError: Utils.handleImageError },
  template: [
    '<div class="row g-3">',
    '  <div class="col-6 col-md-3" v-for="album in albums" :key="album.name + album.artist">',
    '    <div class="card h-100" style="cursor:pointer" @click="$emit(\'view-album\', album)">',
    '      <img :src="album.cover_url || \'\'" class="card-img-top"',
    '           style="height:180px;object-fit:cover" @error="handleImageError">',
    '      <div class="card-body p-3">',
    '        <div class="card-title" style="font-size:14px;margin-bottom:2px">{{ album.name }}</div>',
    '        <div class="card-text" style="font-size:12px">{{ album.artist }}</div>',
    '        <div class="small mt-1">{{ album.track_count }} 首</div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div v-if="!albums.length" class="col-12 empty-state">',
    '    <i class="bi bi-disc"></i>暂无专辑',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 艺术家网格 ── */
var ArtistGrid = {
  name: 'ArtistGrid',
  props: { artists: { type: Array, default: function() { return []; } } },
  emits: ['view-artist'],
  methods: { handleImageError: Utils.handleImageError },
  template: [
    '<div class="row g-3">',
    '  <div class="col-6 col-md-3" v-for="artist in artists" :key="artist.name">',
    '    <div class="card h-100" style="cursor:pointer" @click="$emit(\'view-artist\', artist)">',
    '      <img :src="artist.cover_url || \'\'"',
    '           class="rounded-circle mx-auto mt-3"',
    '           style="height:130px;width:130px;object-fit:cover;display:block"',
    '           @error="handleImageError">',
    '      <div class="card-body text-center p-3">',
    '        <div class="card-title" style="font-size:14px">{{ artist.name }}</div>',
    '        <div class="card-text" style="font-size:12px">',
    '          {{ artist.album_count }} 张专辑 · {{ artist.track_count }} 首',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div v-if="!artists.length" class="col-12 empty-state">',
    '    <i class="bi bi-person"></i>暂无艺术家',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 播放列表视图 ── */
var PlaylistView = {
  name: 'PlaylistView',
  props: {
    playlists:       { type: Array,  default: function() { return []; } },
    currentPlaylist: { type: Object, default: null },
    playlistTracks:  { type: Array,  default: function() { return []; } }
  },
  emits: ['view-playlist', 'delete-playlist', 'create-playlist', 'play-track', 'remove-track', 'play-all', 'back'],
  methods: {
    fmtDate: function(iso) { return Utils.formatDate(iso); },
    fmtDur:  function(s)   { return Utils.formatDuration(s); }
  },
  template: [
    '<div>',
    /* 列表总览 */
    '  <div v-if="!currentPlaylist">',
    '    <div class="d-flex justify-content-between align-items-center mb-3">',
    '      <h4 class="text-white mb-0">我的播放列表</h4>',
    '      <button class="btn btn-primary btn-sm" @click="$emit(\'create-playlist\')">',
    '        <i class="bi bi-plus"></i> 新建',
    '      </button>',
    '    </div>',
    '    <div class="row g-3">',
    '      <div class="col-md-4 col-sm-6" v-for="pl in playlists" :key="pl.id">',
    '        <div class="card h-100" style="cursor:pointer" @click="$emit(\'view-playlist\', pl)">',
    '          <div class="card-body">',
    '            <div class="d-flex align-items-center mb-3 gap-3">',
    '              <div class="rounded-2 d-flex align-items-center justify-content-center flex-shrink-0"',
    '                   style="width:48px;height:48px;background:linear-gradient(135deg,#1ed760,#1aa34a)">',
    '                <i class="bi bi-music-note-list text-white" style="font-size:1.2rem"></i>',
    '              </div>',
    '              <div style="min-width:0">',
    '                <div class="card-title mb-0" style="font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ pl.name }}</div>',
    '                <div class="card-text" style="font-size:12px">{{ pl.track_count || 0 }} 首歌曲</div>',
    '              </div>',
    '            </div>',
    '            <div class="card-text" style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">',
    '              {{ pl.description || "暂无描述" }}',
    '            </div>',
    '          </div>',
    '          <div class="card-footer d-flex justify-content-between align-items-center py-2">',
    '            <small>{{ fmtDate(pl.updated_at) }}</small>',
    '            <button class="btn btn-sm btn-outline-danger" style="padding:2px 8px;font-size:12px"',
    '                    @click.stop="$emit(\'delete-playlist\', pl)">',
    '              <i class="bi bi-trash"></i>',
    '            </button>',
    '          </div>',
    '        </div>',
    '      </div>',
    '      <div v-if="!playlists.length" class="col-12 empty-state">',
    '        <i class="bi bi-list-ul"></i>暂无播放列表',
    '      </div>',
    '    </div>',
    '  </div>',
    /* 详情 */
    '  <div v-if="currentPlaylist">',
    '    <div class="d-flex align-items-center mb-3 gap-2">',
    '      <button class="btn btn-outline-light btn-sm" @click="$emit(\'back\')">',
    '        <i class="bi bi-arrow-left"></i> 返回',
    '      </button>',
    '      <h4 class="mb-0 text-white flex-grow-1">{{ currentPlaylist.name }}</h4>',
    '      <button class="btn btn-primary btn-sm" @click="$emit(\'play-all\')">',
    '        <i class="bi bi-play-fill"></i> 播放全部',
    '      </button>',
    '    </div>',
    '    <div class="table-responsive">',
    '      <table class="table table-hover">',
    '        <thead><tr><th>#</th><th>标题</th><th>艺术家</th><th class="d-none d-md-table-cell">专辑</th><th>时长</th><th>操作</th></tr></thead>',
    '        <tbody>',
    '          <tr v-for="(track, idx) in playlistTracks" :key="track.id">',
    '            <td class="text-secondary">{{ idx + 1 }}</td>',
    '            <td>{{ track.title }}</td>',
    '            <td class="text-secondary" style="font-size:13px">{{ track.artist }}</td>',
    '            <td class="text-secondary d-none d-md-table-cell" style="font-size:13px">{{ track.album }}</td>',
    '            <td class="text-secondary" style="font-size:13px">{{ fmtDur(track.duration) }}</td>',
    '            <td>',
    '              <div class="action-btn-group">',
    '                <button class="btn btn-play btn-icon" @click="$emit(\'play-track\', track)"><i class="bi bi-play-fill"></i></button>',
    '                <button class="btn btn-icon btn-icon-ghost" @click="$emit(\'remove-track\', track)" title="移除"><i class="bi bi-trash"></i></button>',
    '              </div>',
    '            </td>',
    '          </tr>',
    '        </tbody>',
    '      </table>',
    '    </div>',
    '    <div v-if="!playlistTracks.length" class="empty-state">',
    '      <i class="bi bi-music-note-list"></i>播放列表为空',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 收藏列表 ── */
var FavoriteList = {
  name: 'FavoriteList',
  props: { favorites: { type: Array, default: function() { return []; } } },
  emits: ['play', 'toggle-favorite'],
  methods: {
    getCoverUrl:      function(id) { return Utils.getCoverUrl(id); },
    handleImageError: Utils.handleImageError,
    fmtDur:           function(s) { return Utils.formatDuration(s); }
  },
  template: [
    '<div>',
    '  <h4 class="text-white mb-3">',
    '    <i class="bi bi-heart-fill me-2" style="color:var(--negative-red)"></i>我的收藏',
    '  </h4>',
    '  <div class="table-responsive">',
    '    <table class="table table-hover">',
    '      <thead><tr><th>#</th><th>标题</th><th>艺术家</th><th class="d-none d-md-table-cell">专辑</th><th>时长</th><th>操作</th></tr></thead>',
    '      <tbody>',
    '        <tr v-for="(track, idx) in favorites" :key="track.id">',
    '          <td class="text-secondary">{{ idx + 1 }}</td>',
    '          <td>',
    '            <div class="d-flex align-items-center gap-2">',
    '              <img :src="getCoverUrl(track.id)" class="cover-img"',
    '                   style="width:36px;height:36px" @error="handleImageError">',
    '              {{ track.title }}',
    '            </div>',
    '          </td>',
    '          <td class="text-secondary" style="font-size:13px">{{ track.artist }}</td>',
    '          <td class="text-secondary d-none d-md-table-cell" style="font-size:13px">{{ track.album }}</td>',
    '          <td class="text-secondary" style="font-size:13px">{{ fmtDur(track.duration) }}</td>',
    '          <td>',
    '            <div class="action-btn-group">',
    '              <button class="btn btn-play btn-icon" @click="$emit(\'play\', track)"><i class="bi bi-play-fill"></i></button>',
    '              <button class="btn btn-icon btn-icon-ghost fav-active" @click="$emit(\'toggle-favorite\', track)" title="取消收藏">',
    '                <i class="bi bi-heart-fill"></i>',
    '              </button>',
    '            </div>',
    '          </td>',
    '        </tr>',
    '      </tbody>',
    '    </table>',
    '  </div>',
    '  <div v-if="!favorites.length" class="empty-state">',
    '    <i class="bi bi-heart"></i>暂无收藏歌曲',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 最近播放 ── */
var RecentPlays = {
  name: 'RecentPlays',
  props: {
    recentPlays:  { type: Array,  default: function() { return []; } },
    favoritedIds: { type: Object, default: function() { return new Set(); } }
  },
  emits: ['play', 'toggle-favorite', 'remove', 'clear'],
  methods: {
    getCoverUrl:       function(id) { return Utils.getCoverUrl(id); },
    handleImageError:  Utils.handleImageError,
    fmtDur:            function(s)   { return Utils.formatDuration(s); },
    fmtRel:            function(iso) { return Utils.formatRelativeTime(iso); },
    isFav:             function(id)  { return this.favoritedIds.has(id); }
  },
  template: [
    '<div>',
    '  <div class="d-flex justify-content-between align-items-center mb-3">',
    '    <h4 class="text-white mb-0"><i class="bi bi-clock-history me-2"></i>最近播放</h4>',
    '    <button class="btn btn-outline-danger btn-sm" @click="$emit(\'clear\')" v-if="recentPlays.length">',
    '      <i class="bi bi-trash"></i> 清空',
    '    </button>',
    '  </div>',
    '  <div class="table-responsive">',
    '    <table class="table table-hover">',
    '      <thead>',
    '        <tr><th>#</th><th>标题</th><th>艺术家</th><th class="d-none d-md-table-cell">专辑</th>',
    '            <th>时长</th><th class="d-none d-lg-table-cell">播放时间</th><th>操作</th></tr>',
    '      </thead>',
    '      <tbody>',
    '        <tr v-for="(track, idx) in recentPlays" :key="track.id + (track.played_at || \'\')">',
    '          <td class="text-secondary">{{ idx + 1 }}</td>',
    '          <td>',
    '            <div class="d-flex align-items-center gap-2">',
    '              <img :src="getCoverUrl(track.id)" class="cover-img"',
    '                   style="width:36px;height:36px" @error="handleImageError">',
    '              {{ track.title }}',
    '            </div>',
    '          </td>',
    '          <td class="text-secondary" style="font-size:13px">{{ track.artist }}</td>',
    '          <td class="text-secondary d-none d-md-table-cell" style="font-size:13px">{{ track.album }}</td>',
    '          <td class="text-secondary" style="font-size:13px">{{ fmtDur(track.duration) }}</td>',
    '          <td class="text-secondary d-none d-lg-table-cell" style="font-size:13px">{{ fmtRel(track.played_at) }}</td>',
    '          <td>',
    '            <div class="action-btn-group">',
    '              <button class="btn btn-play btn-icon" @click="$emit(\'play\', track)"><i class="bi bi-play-fill"></i></button>',
    '              <button class="btn btn-icon btn-icon-ghost" :class="{ \'fav-active\': isFav(track.id) }"',
    '                      @click="$emit(\'toggle-favorite\', track)">',
    '                <i :class="isFav(track.id) ? \'bi bi-heart-fill\' : \'bi bi-heart\'"></i>',
    '              </button>',
    '              <button class="btn btn-icon btn-icon-ghost" @click="$emit(\'remove\', track)" title="移除">',
    '                <i class="bi bi-x-lg"></i>',
    '              </button>',
    '            </div>',
    '          </td>',
    '        </tr>',
    '      </tbody>',
    '    </table>',
    '  </div>',
    '  <div v-if="!recentPlays.length" class="empty-state">',
    '    <i class="bi bi-clock-history"></i>暂无播放记录',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 管理面板 ── */
var AdminPanel = {
  name: 'AdminPanel',
  props: {
    stats:      { type: Object, default: function() { return {}; } },
    topTracks:  { type: Array,  default: function() { return []; } },
    topPeriod:  { type: String, default: '7d' },
    activities: { type: Array,  default: function() { return []; } }
  },
  emits: ['scan', 'clear-cache', 'load-top-tracks', 'update:topPeriod'],
  computed: {
    statCards: function() {
      return [
        { label: '总曲目',  value: this.stats.total_tracks, icon: 'bi-music-note-list', bg: '#0d6efd' },
        { label: '总用户',  value: this.stats.total_users,  icon: 'bi-people',           bg: '#198754' },
        { label: '总播放',  value: this.stats.total_plays,  icon: 'bi-play-circle',      bg: '#0dcaf0' },
        { label: '今日播放',value: this.stats.today_plays,  icon: 'bi-calendar-check',   bg: '#fd7e14' }
      ];
    }
  },
  methods: {
    fmtNum:  function(n)   { return Utils.formatNumber(n); },
    fmtDt:   function(iso) { return Utils.formatDateTime(iso); },
    actText: function(t)   { return Utils.getActivityText(t); },
    actBadge:function(t)   { return Utils.getActivityBadge(t); }
  },
  template: [
    '<div>',
    '  <h4 class="text-white mb-3"><i class="bi bi-bar-chart-fill me-2"></i>管理仪表盘</h4>',
    /* 统计卡片 */
    '  <div class="row g-3 mb-4">',
    '    <div class="col-6 col-md-3" v-for="card in statCards" :key="card.label">',
    '      <div class="stat-card d-flex justify-content-between align-items-center" :style="\'background:\' + card.bg">',
    '        <div>',
    '          <div style="font-size:1.5rem;font-weight:700">{{ fmtNum(card.value) }}</div>',
    '          <div style="font-size:12px;opacity:.8">{{ card.label }}</div>',
    '        </div>',
    '        <i :class="\'bi \' + card.icon" style="font-size:2rem;opacity:.35"></i>',
    '      </div>',
    '    </div>',
    '  </div>',
    /* 热门 + 活动 */
    '  <div class="row g-3 mb-4">',
    '    <div class="col-md-6">',
    '      <div class="card">',
    '        <div class="card-header d-flex justify-content-between align-items-center">',
    '          <span class="text-white fw-bold" style="font-size:14px"><i class="bi bi-trophy me-2"></i>热门曲目</span>',
    '          <select class="form-select form-select-sm" style="width:auto"',
    '                  :value="topPeriod"',
    '                  @change="$emit(\'update:topPeriod\', $event.target.value); $emit(\'load-top-tracks\')">',
    '            <option value="1d">今日</option>',
    '            <option value="7d">本周</option>',
    '            <option value="30d">本月</option>',
    '            <option value="all">全部</option>',
    '          </select>',
    '        </div>',
    '        <div class="card-body p-0">',
    '          <table class="table table-sm mb-0">',
    '            <thead><tr><th>#</th><th>曲目</th><th class="text-end">播放</th></tr></thead>',
    '            <tbody>',
    '              <tr v-for="(t, i) in topTracks" :key="t.id">',
    '                <td class="text-secondary">{{ i + 1 }}</td>',
    '                <td style="font-size:13px">{{ t.artist }} - {{ t.title }}</td>',
    '                <td class="text-end" style="color:var(--accent-green);font-size:13px">{{ t.play_count }}</td>',
    '              </tr>',
    '              <tr v-if="!topTracks.length"><td colspan="3" class="text-center text-secondary py-3" style="font-size:13px">暂无数据</td></tr>',
    '            </tbody>',
    '          </table>',
    '        </div>',
    '      </div>',
    '    </div>',
    '    <div class="col-md-6">',
    '      <div class="card" style="height:100%">',
    '        <div class="card-header">',
    '          <span class="text-white fw-bold" style="font-size:14px"><i class="bi bi-activity me-2"></i>最近活动</span>',
    '        </div>',
    '        <div class="card-body p-0" style="max-height:340px;overflow-y:auto">',
    '          <div v-for="(act, i) in activities" :key="i"',
    '               style="padding:10px 14px;border-bottom:1px solid rgba(255,255,255,.06)">',
    '            <div class="d-flex align-items-start gap-2">',
    '              <span class="badge" :class="actBadge(act.type)" style="margin-top:2px">{{ actText(act.type) }}</span>',
    '              <div style="min-width:0;flex:1">',
    '                <div class="d-flex justify-content-between">',
    '                  <strong style="font-size:13px">{{ act.username }}</strong>',
    '                  <small class="text-secondary">{{ fmtDt(act.timestamp) }}</small>',
    '                </div>',
    '                <div class="text-secondary" style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" v-if="act.track">',
    '                  {{ act.track }}',
    '                </div>',
    '              </div>',
    '            </div>',
    '          </div>',
    '          <div v-if="!activities.length" class="text-center text-secondary py-4" style="font-size:13px">暂无活动</div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    /* 系统管理 */
    '  <div class="card">',
    '    <div class="card-header">',
    '      <span class="text-white fw-bold" style="font-size:14px"><i class="bi bi-gear me-2"></i>系统管理</span>',
    '    </div>',
    '    <div class="card-body d-flex gap-2">',
    '      <button class="btn btn-warning btn-sm" @click="$emit(\'clear-cache\')">',
    '        <i class="bi bi-trash me-1"></i>清空转码缓存',
    '      </button>',
    '      <button class="btn btn-success btn-sm" @click="$emit(\'scan\')">',
    '        <i class="bi bi-arrow-repeat me-1"></i>扫描媒体库',
    '      </button>',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n')
};

/* ── 播放器栏 ── */
var PlayerBar = {
  name: 'PlayerBar',
  props: {
    currentTrack:    { type: Object,   required: true },
    isPlaying:       { type: Boolean,  default: false },
    currentTime:     { type: Number,   default: 0 },
    duration:        { type: Number,   default: 0 },
    progress:        { type: Number,   default: 0 },
    volume:          { type: Number,   default: 0.8 },
    playModeIcon:    { type: String,   default: 'bi-repeat' },
    playModeText:    { type: String,   default: '顺序播放' },
    showLyrics:      { type: Boolean,  default: false },
    lyrics:          { type: Object,   default: null },
    lyricOffset:     { type: Number,   default: 0 },
    trackOffset:     { type: Number,   default: 0 },     // 轨道 Y 偏移
    getLineClass:    { type: Function, default: function() { return 'lyrics-line'; } },
    lyricLineHeight: { type: Number,   default: 40 }
  },
  emits: [
    'toggle-play-mode', 'prev', 'toggle-play', 'next',
    'toggle-lyrics', 'seek', 'toggle-mute', 'set-volume',
    'show-shortcuts', 'adjust-lyric-offset',
    'lyric-wheel', 'lyric-touch-start', 'lyric-touch-move'
  ],
  methods: {
    getCoverUrl:      function(id) { return Utils.getCoverUrl(id); },
    handleImageError: Utils.handleImageError,
    fmtTime:          function(s)  { return Utils.formatTime(s); },
    volIcon: function() {
      if (this.volume === 0) return 'bi-volume-mute';
      return this.volume < 0.5 ? 'bi-volume-down' : 'bi-volume-up';
    }
  },
  mounted: function() {
    // 设置 CSS 变量供歌词容器使用
    document.documentElement.style.setProperty(
      '--lyric-line-height', this.lyricLineHeight + 'px'
    );
  },
  template: [
    '<div class="player-bar">',
    '  <div class="container-fluid px-0">',
    '    <div class="row align-items-center g-0">',

    // ── 左：封面 + 信息 ──
    '      <div class="col-md-3 col-4 pe-2">',
    '        <div class="d-flex align-items-center gap-2">',
    '          <img :src="getCoverUrl(currentTrack.id)" class="cover-img flex-shrink-0"',
    '               style="width:52px;height:52px" @error="handleImageError">',
    '          <div style="min-width:0">',
    '            <div class="text-white fw-bold"',
    '                 style="font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">',
    '              {{ currentTrack.title }}',
    '            </div>',
    '            <div class="text-secondary"',
    '                 style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">',
    '              {{ currentTrack.artist || "未知艺术家" }}',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',

    // ── 中：播放控制 + 进度条 ──
    '      <div class="col-md-6 col-4">',
    '        <div class="d-flex flex-column align-items-center">',
    '          <div class="player-controls mb-2">',
    '            <button class="player-btn" @click="$emit(\'toggle-play-mode\')" :title="playModeText">',
    '              <i :class="\'bi \' + playModeIcon"></i>',
    '            </button>',
    '            <button class="player-btn" @click="$emit(\'prev\')" title="上一曲">',
    '              <i class="bi bi-skip-start-fill"></i>',
    '            </button>',
    '            <button class="player-btn player-btn-play" @click="$emit(\'toggle-play\')"',
    '                    title="播放/暂停">',
    '              <i :class="\'bi \' + (isPlaying ? \'bi-pause-fill\' : \'bi-play-fill\')"></i>',
    '            </button>',
    '            <button class="player-btn" @click="$emit(\'next\')" title="下一曲">',
    '              <i class="bi bi-skip-end-fill"></i>',
    '            </button>',
    '            <button class="player-btn" :class="{ active: showLyrics }"',
    '                    @click="$emit(\'toggle-lyrics\')" title="歌词">',
    '              <i class="bi bi-file-text"></i>',
    '            </button>',
    '          </div>',
    '          <div class="progress-container">',
    '            <span class="time-text">{{ fmtTime(currentTime) }}</span>',
    '            <div class="progress-slider">',
    '              <input type="range" class="progress-range"',
    '                     :value="progress"',
    '                     @input="$emit(\'seek\', $event.target.value)"',
    '                     min="0" max="100" step="0.1">',
    '            </div>',
    '            <span class="time-text">{{ fmtTime(duration) }}</span>',
    '          </div>',
    '        </div>',
    '      </div>',

    // ── 右：音量控制 ──
    '      <div class="col-md-3 col-4">',
    '        <div class="d-flex align-items-center justify-content-end gap-1">',
    '          <button class="player-btn d-none d-md-flex"',
    '                  @click="$emit(\'show-shortcuts\')" title="快捷键">',
    '            <i class="bi bi-keyboard"></i>',
    '          </button>',
    '          <button class="player-btn" @click="$emit(\'toggle-mute\')" title="静音">',
    '            <i :class="\'bi \' + volIcon()"></i>',
    '          </button>',
    '          <div class="volume-slider d-none d-md-block">',
    '            <input type="range" class="volume-range"',
    '                   :value="volume"',
    '                   @input="$emit(\'set-volume\', parseFloat($event.target.value))"',
    '                   min="0" max="1" step="0.01">',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',

    // ── 歌词区域 ──
    '    <div class="mt-3" v-if="showLyrics">',

    //   偏移调节栏
    '      <div class="lyrics-header">',
    '        <div class="btn-group btn-group-sm">',
    '          <button class="btn btn-outline-light" style="font-size:11px;padding:3px 8px"',
    '                  @click="$emit(\'adjust-lyric-offset\', -100)">',
    '            <i class="bi bi-arrow-left"></i> -0.1s',
    '          </button>',
    '          <span class="btn btn-outline-light disabled"',
    '                style="font-size:11px;padding:3px 8px">',
    '            {{ lyricOffset }}ms',
    '          </span>',
    '          <button class="btn btn-outline-light" style="font-size:11px;padding:3px 8px"',
    '                  @click="$emit(\'adjust-lyric-offset\', 100)">',
    '            +0.1s <i class="bi bi-arrow-right"></i>',
    '          </button>',
    '        </div>',
    '      </div>',

    //   有歌词时显示滚动轨道
    '      <template v-if="lyrics && lyrics.lines && lyrics.lines.length">',
    '        <div class="lyrics-container"',
    '             @wheel.prevent="$emit(\'lyric-wheel\', $event)"',
    '             @touchstart.passive="$emit(\'lyric-touch-start\', $event)"',
    '             @touchmove.prevent="$emit(\'lyric-touch-move\', $event)">',
    '          <div class="lyrics-track"',
    '               :style="{ transform: \'translateY(\' + trackOffset + \'px)\' }">',
    '            <div v-for="(line, idx) in lyrics.lines"',
    '                 :key="idx"',
    '                 :class="getLineClass(idx)"',
    '                 :style="{ height: lyricLineHeight + \'px\' }">',
    '              {{ line.text || \'♪\' }}',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </template>',

    //   无歌词时显示占位
    '      <div v-else class="lyrics-empty">',
    '        <i class="bi bi-file-text"',
    '           style="font-size:2rem;opacity:.3;display:block;margin-bottom:6px"></i>',
    '        暂无歌词',
    '      </div>',

    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n')
};
